# Generated by Django 5.1.2 on 2024-10-10 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_flight',
            name='depart_date',
            field=models.DateTimeField(default=datetime.date(2024, 10, 10)),
        ),
        migrations.AlterField(
            model_name='s_flight',
            name='return_date',
            field=models.DateTimeField(default=datetime.date(2024, 10, 10)),
        ),
    ]
