# Generated by Django 5.1.2 on 2024-10-24 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_s_flight_depart_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_flight',
            name='depart_date',
            field=models.DateTimeField(default=datetime.date(2024, 10, 24)),
        ),
        migrations.AlterField(
            model_name='s_flight',
            name='return_date',
            field=models.DateTimeField(default=datetime.date(2024, 10, 24)),
        ),
    ]
