# Generated by Django 5.1.2 on 2024-11-21 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_s_flight_depart_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(default='profile_photos/default.png', upload_to='profile_photos/')),
            ],
        ),
        migrations.AlterField(
            model_name='s_flight',
            name='depart_date',
            field=models.DateTimeField(default=datetime.date(2024, 11, 21)),
        ),
        migrations.AlterField(
            model_name='s_flight',
            name='return_date',
            field=models.DateTimeField(default=datetime.date(2024, 11, 21)),
        ),
    ]
