# Generated by Django 5.1.2 on 2024-11-22 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_admin_alter_s_flight_depart_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='s_flight',
            name='depart_date',
            field=models.DateTimeField(default=datetime.date(2024, 11, 22)),
        ),
        migrations.AlterField(
            model_name='s_flight',
            name='return_date',
            field=models.DateTimeField(default=datetime.date(2024, 11, 22)),
        ),
    ]
